# Generated by Django 3.0.14 on 2023-02-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_authuser_tbcalendariovacina_tbloginusuario_tbmunicipiobrasil_tbmunicipios_tbubsdadosbrasil_tbubsdado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vacinas',
        ),
        migrations.AlterModelOptions(
            name='tbcalendariovacina',
            options={'managed': False, 'verbose_name': 'Tabela de monitor', 'verbose_name_plural': 'Cadastro de Vacinas'},
        ),
        migrations.AlterModelOptions(
            name='tbmunicipios',
            options={'managed': False, 'verbose_name': 'Tabela de municipio', 'verbose_name_plural': 'Cadastro de Municipios'},
        ),
        migrations.AlterModelOptions(
            name='tbubsdadossp',
            options={'managed': False, 'verbose_name': 'Tabela de UBS', 'verbose_name_plural': 'Cadastro de UBS'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='users/%Y/%m/%d/', verbose_name='Foto'),
        ),
    ]
