# Generated by Django 3.0.14 on 2023-02-26 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_auto_20230225_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbParametros',
            fields=[
                ('id_parametro', models.AutoField(primary_key=True, serialize=False)),
                ('parametro', models.CharField(max_length=50, verbose_name='Parametro de configuração')),
                ('valor', models.IntegerField(verbose_name='Valor do Parametro')),
            ],
            options={
                'verbose_name': 'Tabela de Parametros',
                'verbose_name_plural': 'Cadastro de Parametros',
                'db_table': 'tb_parametros',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='TbParametrizacao',
        ),
    ]
