# Generated by Django 3.0.14 on 2023-02-25 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacina', '0004_tbparametrizacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbparametrizacao',
            options={'managed': False, 'verbose_name': 'Tabela para Parametrização', 'verbose_name_plural': 'Cadastro de Parametros'},
        ),
    ]
